version: '3'
services:
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    build: .
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data:/usr/etc/rabbitmq/data
    restart: always