version:  '3'
services:
    emqx:
      image:  emqx/emqx:latest
      container_name:  emqx
      ports:
        -  "1883:1883"  #  MQTT  客户端连接端口
        -  "8083:8083"  #  HTTP  API  端口
        -  "18083:18083"  #  Dashboard  端口
      environment:
        -  EMQX_LOADED_PLUGINS="emqx_dashboard,emqx_retainer,emqx_webhook"
      volumes:
        -  ./data:/opt/emqx/data  #  挂载数据卷
        -  ./logs:/opt/emqx/logs  #  挂载日志卷
      restart:  always