version: '3.8'  # 指定Docker Compose文件的版本。3.8版本支持较多的新特性和配置选项。

services:
  powerjob-server:  # 定义一个名为powerjob-server的服务。
    image: powerjob/powerjob-server:latest  # 使用来自powerjob的最新版本的powerjob-server镜像。
    container_name: powerjob-server  # 将创建的容器命名为powerjob-server，便于管理和识别。
    restart: always  # 配置容器自动恢复策略，总是重启容器以提高稳定性和可靠性。
    environment:  # 设置环境变量，传递给容器内的应用程序。
      - TZ=Asia/Shanghai  # 设置时区为Asia/Shanghai，使日志和操作符合该时区。
      - JVMOPTIONS=  # 可选：用于设置JVM的启动选项，目前为空。
      - PARAMS= >  # 一些启动参数，传递给应用程序。
        --spring.profiles.active=product  # 激活Spring的product配置文件，通常用于生产环境的特定配置。
        --spring.datasource.core.jdbc-url=[数据库地址] # 设置MySQL数据库的连接URL，连接到powerjob数据库，使用UTF-8编码。
        --spring.datasource.core.username=[数据库账号]  # 数据库连接的用户名。
        --spring.datasource.core.password=[数据库密码]  # 数据库连接的密码。
        --oms.auth.initiliaze.admin.password=admin  # 初始化管理员账号的密码。
        --spring.mail.host=smtp.qq.com  # 设置邮件服务器的主机。
        --spring.mail.port=25  # 设置邮件服务器的端口。
        --spring.mail.username=[邮箱]  # 设置邮件服务器的用户名。
        --spring.mail.from=[邮箱]  # 设置邮件发送者的邮箱。
        --spring.mail.password=[QQ邮箱是授权码其余邮箱则是密码]  # （注意安全性）设置邮件服务器的密码。
        --spring.mail.properties.mail.smtp.auth=true  # 启用SMTP认证。
        --spring.mail.properties.mail.smtp.starttls.enable=true  # 启用STARTTLS加密。
        --spring.mail.properties.mail.smtp.starttls.required=true  # 要求STARTTLS加密。
        --spring.mail.test.connection=true  # 启动时测试邮件服务器连接。
    ports:
      - "7700:7700"  # 将主机的7700端口映射到容器的7700端口，用于应用程序的外部访问。
      - "10086:10086"  # 将主机的10086端口映射到容器的10086端口。
      - "10010:10010"  # 将主机的10010端口映射到容器的10010端口。
    volumes:
      - ./logs:/root/powerjob/logs  # 挂载本地主机的logs目录到容器内的/root/powerjob/logs，用于存储应用日志。
