version: '3.8'

services:
  powerjob-server:
    image: powerjob/powerjob-server:latest
    container_name: powerjob-server
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - JVMOPTIONS=
      - PARAMS= >
        --spring.profiles.active=product
        --spring.datasource.core.jdbc-url=jdbc:mysql://192.168.8.96:3306/powerjob?useUnicode=true&characterEncoding=UTF-8
        --spring.datasource.core.username=root
        --spring.datasource.core.password=root
        --oms.auth.initiliaze.admin.password=admin
    ports:
      - "7700:7700"
      - "10086:10086"
      - "10010:10010"
    volumes:
      - ./logs:/root/powerjob/logs
