version: '3.8'
services:
## 登陆页面账号 admin 密码 123456
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.1
    container_name: xxl-job-admin
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/xxl-job?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      XXL_JOB_ACCESS_TOKEN: "default_token"
      XXL_JOB_LOG_PATH: "/data/applogs/xxl-job"
      SPRING_MAIL_HOUST: smtp.qq.com
      SPRING_MAIL_PORT: 25
      #发送人邮箱
      SPRING_MAIL_USERNAME:
      #发送人邮箱
      SPRING_MAIL_FROM:
      #如果是QQ邮箱则是授权码,其余的就是密码
      SPRING_MAIL_PASSWORD:

    volumes:
      - ./logs:/data/applogs/xxl-job
