version: '3.8'
services:
  ## XXL-Job 管理服务
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.1
    container_name: xxl-job-admin
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/xxl-job?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      XXL_JOB_ACCESS_TOKEN: "default_token"
      XXL_JOB_LOG_PATH: "/data/applogs/xxl-job"

      # 邮件服务配置
      SPRING_MAIL_HOST: "smtp.qq.com"
      SPRING_MAIL_PORT: "587"  # 测试时也可以试用 465 端口
      SPRING_MAIL_USERNAME: "邮箱"
      SPRING_MAIL_FROM: "邮箱"
      SPRING_MAIL_PASSWORD: "你的QQ邮箱授权码"

      # 邮件服务额外配置
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "true"
      SPRING_MAIL_TEST_CONNECTION: "true"

    volumes:
      - ./logs:/data/applogs/xxl-job
