version: '3.8'  # 指定Docker Compose文件的版本。3.8是一个相对较新的版本，支持更多的功能和配置选项。

services:
  ## XXL-Job 管理服务
  xxl-job-admin:  # 定义一个服务，名为xxl-job-admin。
    image: xuxueli/xxl-job-admin:2.4.1  # 使用xuxueli提供的xxl-job-admin镜像，版本为2.4.1。
    container_name: xxl-job-admin  # 设置容器的名称为xxl-job-admin，方便识别和管理。
    ports:
      - "8080:8080"  # 将主机的8080端口映射到容器的8080端口，以便外部访问XXL-Job的管理界面。
    environment:  # 设置传递给容器的环境变量。
      - TZ=Asia/Shanghai  # 设置时区为Asia/Shanghai，确保应用时间符合本地时区。
      - JVMOPTIONS=  # （可选）指定Java虚拟机的启动选项，目前为空。
      - PARAMS= |  # 设置应用启动参数，这里使用管道符号 `|` 允许多行字符串。
        --spring.datasource.url=[数据库URL]  # 配置数据库的连接URL。
        --spring.datasource.username=[数据库账号]  # 配置数据库连接所需的用户名。
        --spring.datasource.password=[数据库密码]  # 配置数据库连接所需的密码。
        --xxl.job.accessToken=[xxlJob的默认token]  # 设置XXL-Job的访问令牌，确保安全访问。
        --xxl.job.log.path=/data/applogs/xxl-job  # 设置XXL-Job日志文件的存储路径。
        --spring.mail.host=smtp.qq.com  # 指定邮件服务器主机为QQ的SMTP服务器。
        --spring.mail.port=25  # 设置邮件服务器的端口为25。
        --spring.mail.username=[邮箱]  # 配置用于发送邮件的邮箱用户名。
        --spring.mail.from=[邮箱]  # 设置邮件的发件人邮箱地址。
        --spring.mail.password=[QQ邮箱则是授权码,其他邮箱则是密码]  # 配置邮箱的密码或QQ邮箱的授权码。
        --spring.mail.properties.mail.smtp.auth=true  # 启用SMTP认证。
        --spring.mail.properties.mail.smtp.starttls.enable=true  # 启用TLS支持。
        --spring.mail.properties.mail.smtp.starttls.required=true  # 要求使用TLS。
        --spring.mail.test.connection=true  # 在启动时测试邮件服务器的连接。
    volumes:
      - ./logs:/data/applogs/xxl-job  # 将主机上的logs目录挂载到容器内的/data/applogs/xxl-job路径，用于持久化存储日志文件。
