version: '3.8'

services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./data:/data
      - ./logs:/datalog
      - /etc/localtime:/etc/localtime # 容器与宿主机时间同步
    restart: always