version: '3'
services:
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data:/usr/etc/rabbitmq/data
      - /etc/localtime:/etc/localtime # 容器与宿主机时间同步
    restart: always
