version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root #账号
      MONGO_INITDB_ROOT_PASSWORD: root #密码
    restart:  always
