i18n:
  all-locale: zh,en
  language: zh
  path: i18n/messages
server:
  port: 8001
knife4j:
  title: rabbitmq测试用例
  open: true
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jmx:
    enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
file:
  bucket-name: default
  choice: s3
  endpoint: http://127.0.0.1:9000
  access-key: admin
  secret-key: admin12345678
  file-naming-method: date